### ISSUE TITLE
Sign out on the client does not sign out the user on the server?

### ISSUE THREAD

**Issue by shengjing2019** [openiddict/openiddict-samples#92] opened 2020-06-15 19:39 UTC
I'm running the Velusia sample, when I click on the Sign out button the client application, it does not sign out the user on the server application, is this by design? Is there a way to sign the user out from both the client and server?

**Comment by kevinchalet** [comment] 2020-06-15 19:45
Nice catch, there was a config' issue I fixed in https://github.com/openiddict/openiddict-samples/commit/67f2b5b59c2efe9478151dec4c951cb94b2b39a1.

Thanks.

**Closed by kevinchalet** 2020-06-15 19:45 UTC
Labels: bug

**Comment by shengjing2019** [comment] 2020-06-15 20:27
Thank you for the quick fix. Now it does sign user out on the server, but after that it stays on the server instead of redirecting back to the client.

**Comment by kevinchalet** [comment] 2020-06-15 20:39
I can't reproduce that locally, do you mind taking a video capture of what you're seeing?

**Comment by shengjing2019** [comment] 2020-06-15 21:07
Below is a gif capture of login and logout, and upon logout it stays on the server home page instead of redirecting back to client home page.

I also created a separate protected admin page on the client, if I make a request to the admin page it will ask me to login, but after login it redirects back to client home page not the admin page.

![2020-06-15_14-02-02](https://user-images.githubusercontent.com/66812108/84705853-e5ebe100-af10-11ea-9d9e-45c4f40faa65.gif)

**Comment by kevinchalet** [comment] 2020-06-16 00:16
Thanks for the capture.

There's a bug in beta1: the handler responsible of falling back to the address specified in `AuthenticationProperties.RedirectUri` when calling `SignOut` is not registered at the right place.

You can either remove `RedirectUri = "/"` from the `LogoutPost` endpoint or re-register the handler at the right place:

```csharp
services.AddOpenIddict()
    .AddServer(options =>
    {
        options.RemoveEventHandler(OpenIddictServerAspNetCoreHandlers.ProcessHostRedirectionResponse<ApplyLogoutResponseContext>.Descriptor);
        options.AddEventHandler<ApplyLogoutResponseContext>(builder =>
        {
            builder.AddFilter<RequireHttpRequest>()
                   .UseSingletonHandler<OpenIddictServerAspNetCoreHandlers.ProcessHostRedirectionResponse<ApplyLogoutResponseContext>>()
                   .SetOrder(OpenIddictServerAspNetCoreHandlers.ProcessEmptyResponse<ApplyLogoutResponseContext>.Descriptor.Order - 1_000);
        });
    });
```

It will be fixed in the next release.
