### ISSUE TITLE
CodeFlow. AccessDenied error when a logged user directly go to ~/signin

### ISSUE THREAD

**Issue by ORuban** [openiddict/openiddict-samples#33] opened 2017-02-11 10:20 UTC
I have run CodeFlow sample locally. It works as expected: allows to create a new user and shows all User information on home page.

The problem is that if then I go directly  to `~/signin` I got redirect to `AccessDenied` page and see in logs the `Cookies was forbidden` error:
```
Request starting HTTP/1.1 GET http://localhost:53508/signin  
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware[3]
      HttpContext.User merged via AutomaticAuthentication from authenticationScheme: Cookies.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method ClientApp.Controllers.AuthenticationController.SignIn (ClientApp) with arguments ((null)) - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.ChallengeResult[1]
      Executing ChallengeResult with authentication schemes (OpenIdConnect).
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware[8]
      AuthenticationScheme: Cookies was successfully authenticated.
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware[13]
      AuthenticationScheme: Cookies was forbidden.
info: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectMiddleware[13]
      AuthenticationScheme: OpenIdConnect was forbidden.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action ClientApp.Controllers.AuthenticationController.SignIn (ClientApp) in 0.1443ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 5.5373ms 302 
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:53508/Account/AccessDenied?ReturnUrl=%2F
```

**Comment by PinpointTownes** [comment] 2017-02-11 10:31
By design. The OIDC client middleware detects you're already "logged in" when returning `ChallengeResult` and hijacks the response to return a "forbidden" response instead of the proper challenge you should get.

I've said multiple times this behavior sucked, but nothing has changed:
  - https://github.com/aspnet/Security/issues/273#issuecomment-108536290
  - https://github.com/aspnet/Security/issues/336#issuecomment-119336570
  - https://github.com/aspnet/Security/issues/1061#issuecomment-266092809

@HaoK can we finally consider killing `ChallengeBehavior` in 2.0? :sweat_smile:

**Comment by HaoK** [comment] 2017-02-11 17:19
That's certainly option, how would you prefer the 401 vs 403 logic to work instead?

**Comment by PinpointTownes** [comment] 2017-02-11 17:27
Ideally, the logic should be moved to `IAuthorizationService`, whose `AuthorizeAsync` method would return a complex `AuthorizationResult` containing a `RequireAuthentication` bool property indicating whether the policy evaluation failed due to a lack of authentication or not (e.g by determining whether the failed requirement was `DenyAnonymousAuthorizationRequirement`).

The ultimate `Challenge` vs `Forbidden` decision should be made by the component calling `IAuthorizationService` (e.g https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Authorization/AuthorizeFilter.cs#L160)

This is pretty much the design I had suggested here: https://github.com/PinpointTownes/Security/commit/7ac1a2515015a98dc6f4919f28baa9db33beb50a#diff-7bf20fd130932f29f2028b7126281f84R58

**Comment by HaoK** [comment] 2017-02-11 17:45
Yeah that's pretty much the feeling I had too, where we'd have to make it fully something the AuthZ could distinguish, we can use https://github.com/aspnet/Security/issues/901 to track this, and tackle it after the main 2.0 change is in

**Comment by ORuban** [comment] 2017-02-11 20:27
Thanks for the response, it's clear now.

**Comment by PinpointTownes** [comment] 2017-03-02 11:45
Closing, as future improvements in ASP.NET Core are tracked by https://github.com/aspnet/Security/issues/901.

**Closed** 2017-03-02 11:45 UTC
